### PR TITLE
Fix for issue with global `escape` function being included in template context

### PR DESCRIPTION
**Pull request by paulegan**
I've added a test that shows the issue with the `escape` function and then a fix.

### CODE REVIEW

**Comment by dohzya** [comment]
Thanks for you PR :-)
It's really nice to have added a test!

However… I don't understand what this change fixes :-/
The test passes on my computer (with and without the last commit).

To be honest it seems to me that this last commit does not change anything: the previous version created a sandbox context that was passed to `renderTemplate` and propagated into sub-templates – the new version passes and propagates the `documentSets` directly but uses a sandbox created inside this object.

What did I miss?

Note: I realized that there is a big naming issue: `ctx` is used for 2 unrelated things :-(
I think we should rename it into `sandbox` or `templateCtx` in template helpers.

**Comment by paulegan** [comment]
Interesting that you're getting a different result.

Here's what I see:
```sh
> git st
HEAD detached at 7cb84fb
nothing to commit, working directory clean
> gulp test
[09:38:22] Using gulpfile ~/work/download/baked.js/gulpfile.js
[09:38:22] Starting 'test'...


  ․

  0 passing (917ms)
  1 failing

  1) baked should render correctly:
     Uncaught AssertionError: expected '<!DOCTYPE html>\n\n<html>\n  \n  <head>\n  <title>TEST</title>\n  <link rel="canonical" href="http%3A//localhost/"/>\n</head>\n\n  <body>\n\n    \n\n\n\n\n\n    \n      Tsutomu%20Kabayashi%2C%20Pastry%20Dresser\n    \n  <script>window.routerInfosForFile = {"src":"/index.html","dst":"/index.html","args":null};</script>\n</body>\n</html>\n' to contain 'http://localhost/'
      at test/test.js:36:31



[09:38:23] 'test' errored after 999 ms
[09:38:23] Error in plugin 'gulp-mocha'
Message:
    1 test failed.
```

The values inserted into the template have been run through the builtin `escape()`. This happens after either `require()` or `partial()` are called, because the `vm.runInContext()` call adds this to the template context.

Perhaps you could argue that the fix should be to recommend that EJS not use a builtin function as an identifier within the compiled template. The same effect can be achieved with something like:
```node
>> var ejs = require('ejs')
undefined
>> var lodash = require('lodash')
undefined
>> ejs.render('<%= x %>', lodash.assign({x: 'A test', escape: escape}, global))
'A%20test'
>> 
```

Anyway, if you're getting a different result it suggests that the problem might be initiated elsewhere. Now I'm wondering about versions of node...

**Comment by paulegan** [comment]
I added my full list of node module versions here: https://gist.github.com/paulegan/072c09c4fd8090b988f7 (generated with `npm ll --parseable | sed -e 's,.*baked.js/node_modules/,,' >modules.txt`). It could be interesting to compare with yours.

**Comment by dohzya** [comment]
I have the same versions than you (well… I haven't but I renamed my `node_modules` directory then `npm install` and re-test with success).
Ok there is 1 difference : you use q@1.4.0 and I use 1.4.1… but I suppose there is nothing here.

Maybe the difference is the node version?
I use Node.js v0.12.2 on MacOS 10.10.3.

**Comment by paulegan** [comment]
Confirmed that this was caused by an issue in node internals. `git bisect` narrowed it down to this commit: joyent/node@85898d1. The associated issue was: joyent/node#6208.

I was testing with v0.10. I think anybody running v0.11.7 or earlier would see the issue.

So, what would you like to do with this pull request? The test would definitely be useful going forward I suppose. The second commit is probably only necessary if you want to support users with earlier version of node.

**Comment by dohzya** [comment]
I definitively want to keep the test indeed ;-)

For the other commit, I propose to add a comment to explain why it's useful and to merge it as well :-)

**Comment by paulegan** [comment]
Cool. I've added a comment to `renderTemplate()`.

**Comment by dohzya** [comment]
Perfect, thank you a lot :-)

**Pull request merged**
